app/assets/javascripts/users.js
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
db/migrate/20160829134823_add_columns_to_users.rb
db/migrate/20160829140339_remove_integers_from_users.rb
db/migrate/20160829140832_add_phone_number_and_student_id_to_users.rb
db/schema.rb

Users table has all the columns and created users controller

Updated users schema and created users controller

---

app/models/car.rb
db/migrate/20160829141223_create_cars.rb

Created cars model in db

---

app/models/journey.rb
db/migrate/20160829141800_create_journeys.rb
db/schema.rb

created journey model

---

app/assets/javascripts/profiles.js
app/assets/stylesheets/profiles.scss
app/controllers/profiles_controller.rb
app/helpers/profiles_helper.rb
db/schema.rb

Created show, edit and update methods for profiles controller

Profile controller

---

app/models/passenger.rb
db/migrate/20160829143009_create_passengers.rb

Created passenger model

---

app/assets/javascripts/cars.js
app/assets/stylesheets/cars.scss
app/controllers/cars_controller.rb
app/helpers/cars_helper.rb

Created basic 7 CRUD methods for car controller

Created basic 7 CRUD methods for car controller

---

app/controllers/cars_controller.rb
app/models/car.rb
app/views/cars/_car_form.html.erb
app/views/cars/edit.html.erb
app/views/cars/index.html.erb
app/views/cars/new.html.erb
app/views/cars/show.html.erb
db/migrate/20160829145331_rename_model_column_in_cars.rb
db/schema.rb

Created basic views for car model (index, show, new, edit)

Views for car model

---

app/controllers/profiles_controller.rb
app/controllers/users_controller.rb
app/views/profiles/edit.html.erb
app/views/profiles/show.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/schema.rb

Created profiles#show and profiles#edit views.
User can view and edit their profile

Profiles controller

---

app/assets/javascripts/passengers.js
app/assets/stylesheets/passengers.scss
app/controllers/passengers_controller.rb
app/helpers/passengers_helper.rb
config/routes.rb

Created passenger controller with create and update methods

Passenger controller

---

app/models/car.rb

Presence on all fields and regex for licence plates (VRN)

Added validations for car.rb

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb

Added basic bootstrap grids to forms

Added basic bootstrap grid to devise forms

---

app/controllers/profiles_controller.rb
app/views/profiles/show.html.erb

Add car details to user profile
As a driver, I can add a car
As a driver, I can delete a car

Add car details

---

app/controllers/cars_controller.rb
app/controllers/profiles_controller.rb
app/views/cars/_car_form.html.erb
app/views/cars/show.html.erb
app/views/profiles/show.html.erb

Updated strong params for users controller - changed :model to :name

Fix name bug in car model

---

Gemfile
Gemfile.lock
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20160831114107_add_admin_to_users.rb
db/schema.rb

Created admin dasboard

---

Gemfile
Gemfile.lock
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20160831114107_add_admin_to_users.rb
db/schema.rb
db/seeds.rb

Fixed VRN bug - needed to move the x = 0 out of the loop
Added seats_available field to journeys seed

Updating seed

---

Gemfile
Gemfile.lock
app/views/shared/_navbar.html.erb
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20160831114107_add_admin_to_users.rb
db/schema.rb
db/seeds.rb

Added admin btn to navbar if current_user.admin?

Navbar btns

---

app/views/profiles/dashboard/_overview.html.erb

Fixed avg_rating bug - changed from == 0 to .nil?

Fixed avg_rating bug

---

app/views/profiles/dashboard/_account-settings.html.erb
app/views/profiles/dashboard/_overview-header.html.erb

Fixed strftime bug - DOB can be nil

---

app/controllers/journeys_controller.rb
app/controllers/passengers_controller.rb
app/policies/journey_policy.rb
app/views/journeys/show.html.erb
config/routes.rb
db/schema.rb

Partially fixed bugs - permissions all set to true - need to create new branch

Fixed bugs

---

app/assets/stylesheets/components/_avatars.scss
app/controllers/journeys_controller.rb
app/views/journeys/_card.html.erb

Replaced placeholder photo with profile picture
Added destination

Added profile photo and destination to journey#index

---

app/controllers/cars_controller.rb
app/controllers/profiles_controller.rb
app/views/journeys/show.html.erb
app/views/profiles/dashboard/_journey.html.erb

Fixed various bugs - design flaws e.g. display instance rather than attribute
New car and edit user now redirect to dashboard not profile

Fix heroku bugs

---

app/controllers/journeys_controller.rb
app/controllers/passengers_controller.rb
app/mailers/journey_mailer.rb
app/mailers/passenger_mailer.rb
app/views/journey_mailer/update_journey.html.erb
app/views/passenger_mailer/confirmation_of_booking.html.erb
app/views/passenger_mailer/new_passenger.html.erb
config/locales/en.yml

Passenger receives email confirmation and email if the journey is changed

Updated journey notification

---

app/views/pages/home.html.erb
config/locales/en.yml

Translation dependancy removed for home page

Translation dependancy removed for home page

---

app/controllers/journeys_controller.rb
app/policies/journey_policy.rb
app/views/journeys/index.html.erb

Journeys are only displayed on the index if they are not completed (pundit) and still have seats available (controller)

Journey index logic

---

app/controllers/journeys_controller.rb
app/controllers/passengers_controller.rb
app/models/journey.rb
app/models/location.rb
app/models/passenger.rb
app/models/passenger_location.rb
app/views/journeys/_card.html.erb
app/views/journeys/show.html.erb
config/locales/en.yml
config/locales/es.yml
db/migrate/20160906143810_add_pick_up_location_to_passengers.rb
db/migrate/20160906160740_create_passenger_locations.rb
db/schema.rb
db/seeds.rb

Translate to spanish

---

config/locales/es.yml

Reformated es.yml to ensure validitaty

Reformated es.yml to ensure validitaty

---

app/controllers/journeys_controller.rb
app/views/journeys/_map.html.erb
app/views/pages/home.html.erb

Waypoint is automatically added and route updates when passenger joins the journey

Update route for passenger

---

app/assets/stylesheets/components/_avatars.scss

Set width and height of avatar classes to prevent ovals

Set width and height of avatar classes to prevent ovals

---

app/mailers/application_mailer.rb
app/views/layouts/application.html.erb
config/environments/production.rb
config/initializers/devise.rb

Mailer now sends from contact@liftin.co.uk

Fix mailer

---

app/mailers/passenger_mailer.rb
app/views/passenger_mailer/new_passenger.html.erb

Updated new passenger mailer
